[2024-04-20T19:48:09.456+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_dag_gcp.dbt_run manual__2024-04-20T19:48:08.319248+00:00 [queued]>
[2024-04-20T19:48:09.474+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_dag_gcp.dbt_run manual__2024-04-20T19:48:08.319248+00:00 [queued]>
[2024-04-20T19:48:09.475+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-20T19:48:09.504+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): dbt_run> on 2024-04-20 19:48:08.319248+00:00
[2024-04-20T19:48:09.513+0000] {standard_task_runner.py:60} INFO - Started process 571 to run task
[2024-04-20T19:48:09.517+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dbt_dag_gcp', 'dbt_run', 'manual__2024-04-20T19:48:08.319248+00:00', '--job-id', '199', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmp96h1w7c8']
[2024-04-20T19:48:09.520+0000] {standard_task_runner.py:88} INFO - Job 199: Subtask dbt_run
[2024-04-20T19:48:09.601+0000] {task_command.py:423} INFO - Running <TaskInstance: dbt_dag_gcp.dbt_run manual__2024-04-20T19:48:08.319248+00:00 [running]> on host 8141e76a239d
[2024-04-20T19:48:09.762+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_dag_gcp' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2024-04-20T19:48:08.319248+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-20T19:48:08.319248+00:00'
[2024-04-20T19:48:09.764+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-20T19:48:09.765+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/dags/dbt/***_dbt_gcp && dbt run --profiles-dir .']
[2024-04-20T19:48:09.780+0000] {subprocess.py:86} INFO - Output:
[2024-04-20T19:48:09.784+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: dbt: command not found
[2024-04-20T19:48:09.785+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2024-04-20T19:48:09.803+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-04-20T19:48:09.808+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=dbt_dag_gcp, task_id=dbt_run, execution_date=20240420T194808, start_date=20240420T194809, end_date=20240420T194809
[2024-04-20T19:48:09.832+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 199 for task dbt_run (Bash command failed. The command returned a non-zero exit code 127.; 571)
[2024-04-20T19:48:09.851+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-20T19:48:09.900+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
