[2024-04-20T19:43:38.041+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_dag_gcp.dbt_run manual__2024-04-20T19:43:35.902533+00:00 [queued]>
[2024-04-20T19:43:38.059+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_dag_gcp.dbt_run manual__2024-04-20T19:43:35.902533+00:00 [queued]>
[2024-04-20T19:43:38.060+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-20T19:43:38.087+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): dbt_run> on 2024-04-20 19:43:35.902533+00:00
[2024-04-20T19:43:38.095+0000] {standard_task_runner.py:60} INFO - Started process 488 to run task
[2024-04-20T19:43:38.100+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dbt_dag_gcp', 'dbt_run', 'manual__2024-04-20T19:43:35.902533+00:00', '--job-id', '195', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmptka6bmvg']
[2024-04-20T19:43:38.103+0000] {standard_task_runner.py:88} INFO - Job 195: Subtask dbt_run
[2024-04-20T19:43:38.189+0000] {task_command.py:423} INFO - Running <TaskInstance: dbt_dag_gcp.dbt_run manual__2024-04-20T19:43:35.902533+00:00 [running]> on host 8141e76a239d
[2024-04-20T19:43:38.343+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_dag_gcp' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2024-04-20T19:43:35.902533+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-20T19:43:35.902533+00:00'
[2024-04-20T19:43:38.346+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-20T19:43:38.348+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***dags/dbt/***_dbt_gcp && dbt run --profiles-dir .']
[2024-04-20T19:43:38.366+0000] {subprocess.py:86} INFO - Output:
[2024-04-20T19:43:38.369+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: cd: /opt/***dags/dbt/***_dbt_gcp: No such file or directory
[2024-04-20T19:43:38.370+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-04-20T19:43:38.389+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-04-20T19:43:38.396+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=dbt_dag_gcp, task_id=dbt_run, execution_date=20240420T194335, start_date=20240420T194338, end_date=20240420T194338
[2024-04-20T19:43:38.424+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 195 for task dbt_run (Bash command failed. The command returned a non-zero exit code 1.; 488)
[2024-04-20T19:43:38.474+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-20T19:43:38.518+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
