[2024-04-20T20:18:41.139+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_dag_gcp.dbt_run manual__2024-04-20T20:18:37.605400+00:00 [queued]>
[2024-04-20T20:18:41.157+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_dag_gcp.dbt_run manual__2024-04-20T20:18:37.605400+00:00 [queued]>
[2024-04-20T20:18:41.158+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-20T20:18:41.186+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): dbt_run> on 2024-04-20 20:18:37.605400+00:00
[2024-04-20T20:18:41.195+0000] {standard_task_runner.py:60} INFO - Started process 1081 to run task
[2024-04-20T20:18:41.199+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dbt_dag_gcp', 'dbt_run', 'manual__2024-04-20T20:18:37.605400+00:00', '--job-id', '206', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmpd_6x3wcc']
[2024-04-20T20:18:41.202+0000] {standard_task_runner.py:88} INFO - Job 206: Subtask dbt_run
[2024-04-20T20:18:41.288+0000] {task_command.py:423} INFO - Running <TaskInstance: dbt_dag_gcp.dbt_run manual__2024-04-20T20:18:37.605400+00:00 [running]> on host 8141e76a239d
[2024-04-20T20:18:41.432+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_dag_gcp' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2024-04-20T20:18:37.605400+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-20T20:18:37.605400+00:00'
[2024-04-20T20:18:41.434+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-20T20:18:41.436+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /dags/dbt/***_dbt_gcp && dbt run --profiles-dir .']
[2024-04-20T20:18:41.454+0000] {subprocess.py:86} INFO - Output:
[2024-04-20T20:18:41.457+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: cd: /dags/dbt/***_dbt_gcp: No such file or directory
[2024-04-20T20:18:41.459+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-04-20T20:18:41.479+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-04-20T20:18:41.486+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=dbt_dag_gcp, task_id=dbt_run, execution_date=20240420T201837, start_date=20240420T201841, end_date=20240420T201841
[2024-04-20T20:18:41.516+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 206 for task dbt_run (Bash command failed. The command returned a non-zero exit code 1.; 1081)
[2024-04-20T20:18:41.533+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-20T20:18:41.585+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
