[2024-04-20T19:41:58.548+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_dag_gcp.dbt_run scheduled__2024-04-17T00:00:00+00:00 [queued]>
[2024-04-20T19:41:58.565+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_dag_gcp.dbt_run scheduled__2024-04-17T00:00:00+00:00 [queued]>
[2024-04-20T19:41:58.566+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-20T19:41:58.593+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): dbt_run> on 2024-04-17 00:00:00+00:00
[2024-04-20T19:41:58.602+0000] {standard_task_runner.py:60} INFO - Started process 453 to run task
[2024-04-20T19:41:58.606+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dbt_dag_gcp', 'dbt_run', 'scheduled__2024-04-17T00:00:00+00:00', '--job-id', '191', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmp4mfpgvh0']
[2024-04-20T19:41:58.609+0000] {standard_task_runner.py:88} INFO - Job 191: Subtask dbt_run
[2024-04-20T19:41:58.695+0000] {task_command.py:423} INFO - Running <TaskInstance: dbt_dag_gcp.dbt_run scheduled__2024-04-17T00:00:00+00:00 [running]> on host 8141e76a239d
[2024-04-20T19:41:58.861+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_dag_gcp' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2024-04-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-17T00:00:00+00:00'
[2024-04-20T19:41:58.864+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-20T19:41:58.865+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***dags/dbt/***_dbt_gcp && dbt run . --profiles_dir .']
[2024-04-20T19:41:58.882+0000] {subprocess.py:86} INFO - Output:
[2024-04-20T19:41:58.885+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: cd: /opt/***dags/dbt/***_dbt_gcp: No such file or directory
[2024-04-20T19:41:58.886+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-04-20T19:41:58.907+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-04-20T19:41:58.914+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=dbt_dag_gcp, task_id=dbt_run, execution_date=20240417T000000, start_date=20240420T194158, end_date=20240420T194158
[2024-04-20T19:41:58.937+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 191 for task dbt_run (Bash command failed. The command returned a non-zero exit code 1.; 453)
[2024-04-20T19:41:58.980+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-20T19:41:59.026+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
