[2024-04-20T19:40:51.257+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_dag_gcp.dbt_run scheduled__2024-01-11T00:00:00+00:00 [queued]>
[2024-04-20T19:40:51.276+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_dag_gcp.dbt_run scheduled__2024-01-11T00:00:00+00:00 [queued]>
[2024-04-20T19:40:51.277+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-20T19:40:51.308+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): dbt_run> on 2024-01-11 00:00:00+00:00
[2024-04-20T19:40:51.316+0000] {standard_task_runner.py:60} INFO - Started process 149 to run task
[2024-04-20T19:40:51.322+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dbt_dag_gcp', 'dbt_run', 'scheduled__2024-01-11T00:00:00+00:00', '--job-id', '94', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmp1bdnny84']
[2024-04-20T19:40:51.327+0000] {standard_task_runner.py:88} INFO - Job 94: Subtask dbt_run
[2024-04-20T19:40:51.420+0000] {task_command.py:423} INFO - Running <TaskInstance: dbt_dag_gcp.dbt_run scheduled__2024-01-11T00:00:00+00:00 [running]> on host 8141e76a239d
[2024-04-20T19:40:51.590+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_dag_gcp' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2024-01-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-11T00:00:00+00:00'
[2024-04-20T19:40:51.592+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-20T19:40:51.594+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***dags/dbt/***_dbt_gcp && dbt run . --profiles_dir .']
[2024-04-20T19:40:51.615+0000] {subprocess.py:86} INFO - Output:
[2024-04-20T19:40:51.618+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: cd: /opt/***dags/dbt/***_dbt_gcp: No such file or directory
[2024-04-20T19:40:51.619+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-04-20T19:40:51.640+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-04-20T19:40:51.647+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=dbt_dag_gcp, task_id=dbt_run, execution_date=20240111T000000, start_date=20240420T194051, end_date=20240420T194051
[2024-04-20T19:40:51.675+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 94 for task dbt_run (Bash command failed. The command returned a non-zero exit code 1.; 149)
[2024-04-20T19:40:51.694+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-20T19:40:51.773+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
