[2024-04-20T20:59:23.361+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_dag_gcp.dbt_run manual__2024-04-20T20:59:21.722529+00:00 [queued]>
[2024-04-20T20:59:23.369+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_dag_gcp.dbt_run manual__2024-04-20T20:59:21.722529+00:00 [queued]>
[2024-04-20T20:59:23.369+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-20T20:59:23.381+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): dbt_run> on 2024-04-20 20:59:21.722529+00:00
[2024-04-20T20:59:23.385+0000] {standard_task_runner.py:60} INFO - Started process 135 to run task
[2024-04-20T20:59:23.388+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dbt_dag_gcp', 'dbt_run', 'manual__2024-04-20T20:59:21.722529+00:00', '--job-id', '234', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmpnactu45_']
[2024-04-20T20:59:23.389+0000] {standard_task_runner.py:88} INFO - Job 234: Subtask dbt_run
[2024-04-20T20:59:23.429+0000] {task_command.py:423} INFO - Running <TaskInstance: dbt_dag_gcp.dbt_run manual__2024-04-20T20:59:21.722529+00:00 [running]> on host 7a17ca41a0d4
[2024-04-20T20:59:23.489+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_dag_gcp' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2024-04-20T20:59:21.722529+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-20T20:59:21.722529+00:00'
[2024-04-20T20:59:23.490+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-20T20:59:23.491+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/dags/dbt/***_dbt_gcp && dbt run --profiles-dir .']
[2024-04-20T20:59:23.500+0000] {subprocess.py:86} INFO - Output:
[2024-04-20T20:59:23.501+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: dbt: command not found
[2024-04-20T20:59:23.502+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2024-04-20T20:59:23.510+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-04-20T20:59:23.513+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=dbt_dag_gcp, task_id=dbt_run, execution_date=20240420T205921, start_date=20240420T205923, end_date=20240420T205923
[2024-04-20T20:59:23.523+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 234 for task dbt_run (Bash command failed. The command returned a non-zero exit code 127.; 135)
[2024-04-20T20:59:23.560+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-20T20:59:23.583+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
