[2024-04-20T20:25:43.193+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_dag_gcp.dbt_run manual__2024-04-20T20:25:39.085042+00:00 [queued]>
[2024-04-20T20:25:43.211+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_dag_gcp.dbt_run manual__2024-04-20T20:25:39.085042+00:00 [queued]>
[2024-04-20T20:25:43.212+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-20T20:25:43.240+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): dbt_run> on 2024-04-20 20:25:39.085042+00:00
[2024-04-20T20:25:43.249+0000] {standard_task_runner.py:60} INFO - Started process 162 to run task
[2024-04-20T20:25:43.253+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dbt_dag_gcp', 'dbt_run', 'manual__2024-04-20T20:25:39.085042+00:00', '--job-id', '216', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmpl1nmysol']
[2024-04-20T20:25:43.256+0000] {standard_task_runner.py:88} INFO - Job 216: Subtask dbt_run
[2024-04-20T20:25:43.340+0000] {task_command.py:423} INFO - Running <TaskInstance: dbt_dag_gcp.dbt_run manual__2024-04-20T20:25:39.085042+00:00 [running]> on host faf1dc8ef394
[2024-04-20T20:25:43.475+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_dag_gcp' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2024-04-20T20:25:39.085042+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-20T20:25:39.085042+00:00'
[2024-04-20T20:25:43.477+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-20T20:25:43.479+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /dags/dbt/***_dbt_gcp/ && dbt run --profiles-dir .']
[2024-04-20T20:25:43.496+0000] {subprocess.py:86} INFO - Output:
[2024-04-20T20:25:43.499+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: cd: /dags/dbt/***_dbt_gcp/: No such file or directory
[2024-04-20T20:25:43.500+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-04-20T20:25:43.519+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-04-20T20:25:43.525+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=dbt_dag_gcp, task_id=dbt_run, execution_date=20240420T202539, start_date=20240420T202543, end_date=20240420T202543
[2024-04-20T20:25:43.548+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 216 for task dbt_run (Bash command failed. The command returned a non-zero exit code 1.; 162)
[2024-04-20T20:25:43.588+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-20T20:25:43.632+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
